src_files = Split("""main.cc
                     component.cc
                     object.cc
                     objectmanager.cc
                     event_id.h
                     event_id.cc
                     observer.cc
                     observer.h
                     subject.cc
                     subject.h""")

WREN_LIB_PATH = 'wren/lib'
WREN_INCLUDE_PATH = 'wren/src/include'

env = DefaultEnvironment()
env.Append(CPPPATH=[WREN_INCLUDE_PATH])
env.Program('Spectre', src_files, LIBS=['libwren'], LIBPATH=[WREN_LIB_PATH])